name: Deploy to Server

on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Você deve adicionar a chave privada SSH como um segredo no GitHub

      - name: Deploy to Server
        run: |
          # Comandos para fazer o deploy no seu servidor usando SSH
          # ssh ubuntu@213.163.247.214 "cd /var/www/html/ && git pull origin main"
          ssh -i ${{ secrets.chave-privada.pem }} ubuntu@213.163.247.214

